version: '3.9'

volumes:
  esdata:
  kibanadata:

services:

  elasticsearch:
    image: elasticsearch:8.0.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      # Allow cors for client elasticvue
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8080
      # Disable security
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      # Limit RAM usage
      - ES_JAVA_OPTS=-Xms512m -Xmx2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
    labels:
      # Set hints for filebeat
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_co_elastic_logsjson
      co.elastic.logs/enabled: "true"
      co.elastic.logs/module: "elasticsearch"
      co.elastic.logs/fileset.stdout: "access"
      co.elastic.logs/fileset.stderr: "error"

    # Adapted from https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
  filebeat:
    build: ./filebeat
    restart: unless-stopped
    user: root
    environment:
      - strict.perms=false
      - ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Set hints for filebeat
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_co_elastic_logsjson
      co.elastic.logs/enabled: "true"
      co.elastic.logs/json.keys_under_root: "true"
      co.elastic.logs/json.overwrite_keys: "true"
      co.elastic.logs/json.add_error_key: "true"
      co.elastic.logs/json.expand_keys: "true"
  #      co.elastic.logs/json.message_key: "true"

  kibana:
    image: kibana:8.0.0
    restart: unless-stopped
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      # Set hints for filebeat
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_co_elastic_logsjson
      co.elastic.logs/enabled: "true"